### ISSUE TITLE
rocketchat.APISections missing

### ISSUE THREAD

**Issue by HoffErik-JohnerInst** [jadolg/rocketchat_API#109]
Hello,

I have a program that ran without issues until I just updated my imports. Now it's throwing

`from rocketchat_API.APISections.assets import RocketChatAssets
ModuleNotFoundError: No module named 'rocketchat_API.APISections'`

This is my code:

```
from rocketchat_API.rocketchat import RocketChat
import requests
import pprint


def rocket_post():
    # Sign in Rocketchat
    rocket = RocketChat('user', 'password', server_url='https://here_is_my_url')
    pprint(rocket.me().json())
    pprint(rocket.channels_list().json())
    a = rocket.chat_post_message('Dis a message', channel='general', alias='Cookie').json()
    message = a["message"]
    message_id = message["_id"]
    # Pin Message Rocketchat
    pprint(rocket.chat_pin_message(message_id).json())
rocket_post()
```

I am using
Python 3.9
rocketchat_API 1.12.0

As I already said: It ran well until I updated.
Is there any way to get this running again?

**Comment by jadolg** [comment]
Solved in 7f72ac0
I forgot to add the new package to the `setup.py` file :facepalm: 
Thank you so much for reporting it :smile:
