### ISSUE TITLE
how to send a picture in a message

### ISSUE THREAD

**Issue by kaishijeng** [jadolg/rocketchat_API#119]
How to use chat_post_message to send a picture which is stored in a local directory?

Thanks,

**Comment by seattle** [comment]
+1

**Comment by jadolg** [comment]
[The documentation](https://docs.rocket.chat/api/rest-api/methods/chat/postmessage) does not say if this can be done. AFAICT, it is only possible to do it from a URL like this:
```python
rocket.chat_post_message('this is an image', 
                         channel='GENERAL', 
                         attachments=[{"image_url": "https://avatars.dicebear.com/api/bottts/rocket.svg"}]
                         )
```
Or you can use `rooms_upload` instead, but in this case, it shows as a file so it won't show a preview.
