### ISSUE TITLE
RocketConnectionException when login in

### ISSUE THREAD

**Issue by hrapanoel** [jadolg/rocketchat_API#121]
I am trying to login with

```RocketChat(username, pw, server_url=server_url)```

and I get the following error

```
---------------------------------------------------------------------------
RocketConnectionException                 Traceback (most recent call last)
<ipython-input-10-20cde2dcffc7> in <module>
----> 1 rocket = RocketChat(username, pw, server_url=server_url)

~/miniconda3/envs/py37/lib/python3.7/site-packages/rocketchat_API/APISections/base.py in __init__(self, user, password, auth_token, user_id, server_url, ssl_verify, proxies, timeout, session, client_certs)
     34         self.req = session or requests
     35         if user and password:
---> 36             self.login(user, password)  # skipcq: PTC-W1006
     37         if auth_token and user_id:
     38             self.headers["X-Auth-Token"] = auth_token

~/miniconda3/envs/py37/lib/python3.7/site-packages/rocketchat_API/APISections/base.py in login(self, user, password)
    138             return login_request
    139 
--> 140         raise RocketConnectionException()
    141 
    142     def logout(self, **kwargs):

RocketConnectionException: 

```
Then I tried a curl request using

```curl https://path.to/url/api/v1/login -d "user=myuser&password=mypassword"```
and
```curl -H 'Content-type:application/json' https://path.to/url/api/v1/login -d '{"user": "myuser", "password": "mypassword"}'```

Both give me:
```
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
```
 I was able to login previously but then I started getting those errors. I do not know what the problem is. Is it from my code?

**Comment by jadolg** [comment]
This looks like you are having issues with your server setup. You should get a `RocketConnectionException` if the lib is not able to login to the server. It can be the credentials are wrong or the API is just not working. From your curl attempts below, I would say it's the second.
