### ISSUE TITLE
Endpoint users.update

### ISSUE THREAD

**Issue by JayBraker** [jadolg/rocketchat_API#129]
When calling users.update with the following call:
`logged_rocket.users_update(user_id=me["_id"], data={"name": "Lalalalalalal"}).json()`
It doesn't seem to update the name or any other attribute included in the data dict.
However calling the endpoint directly by `logged_rocket.call_api_post("users.update", userId=me["_id"], data={"name": "Lalalalalalal"}).json()` works as expected.
Any ideas why?

Full script:
```
logged_rocket = RocketChat("user1", "password")

me = logged_rocket.me().json()
print(logged_rocket.users_update(user_id=me["_id"], data={"name": "Lalalalalalal"}).json())
print(logged_rocket.call_api_post("users.update", userId=me["_id"], data={"name": "Lalalalalalal"}).json())

The server is fresh setup docker instance using your docker-compose-test-server
```

**Comment by JayBraker** [comment]
Esp weird as the test didn't fail...

**Comment by JayBraker** [comment]
Oookay not sure if this is intended.
For reference to the dev doc: https://developer.rocket.chat/api/rest-api/endpoints/team-collaboration/users/update

Expected params are 
- userId (required)
- data.name (optional)
- data.mail (optioal) etc

Not encapsulating name, mail, roles etc in a JSON object/dict works. However this is not the format described in the docs.

**Comment by jadolg** [comment]
Looks like I made an incorrect assumption when coding this endpoint and mapped anything different from the userId into data. That might be the reason why the test for this method stopped working specifically for the name even when the name. Let me give it another look.

**Comment by jadolg** [comment]
So, actually, it seems to be working now. I just wrote the method in a way you don't need to create a data object, so an update would go like:
```python
logged_rocket.users_update(
        user_id,
        email="anewemailhere@domain.com",
        name="newname",
        password=user.password,
        username="newusername",
    ).json()
```
