### ISSUE TITLE
Subscriptions?

### ISSUE THREAD

**Issue by dfpena** [jadolg/rocketchat_API#13]
Probably not within the scope of this project, but is there a REST equivalent for unread messages? 
https://rocket.chat/docs/developer-guides/realtime-api/method-calls/get-subscriptions/#get-subscriptions

**Comment by jadolg** [comment]
I wrote a bot using the REST API, but what I actually did was reading all text from last message read timestamp to present

**Comment by jadolg** [comment]
maybe this can help https://github.com/jadolg/RocketChatBot
