### ISSUE TITLE
Please add users.createtoken api 

### ISSUE THREAD

**Issue by lsaint** [jadolg/rocketchat_API#135]
https://developer.rocket.chat/api/rest-api/endpoints/team-collaboration-endpoints/users/createtoken
https://developer.rocket.chat/api/rest-api/endpoints/team-collaboration-endpoints/users/removeothertokens

thanks

**Comment by lcundiff** [comment]
Currently this doesn't appear to be working on my end: 

```
    login = ROCKET.login(username,password).json()
    rocket = RocketChat(
      user_id=login.get("data").get("userId"), 
      auth_token=login.get("data").get("authToken"),
      server_url=ROCKET_URL
    )
    users_create_token = rocket.users_create_token(
        username=username
    ).json()
    ```
    
Seems to always return authentication error. Should this be a separate issue?

**Comment by jadolg** [comment]
Double-check your authentication. This works for me just fine:
```python
from rocketchat_API.rocketchat import RocketChat

rocket = RocketChat(
server_url="http://localhost:3000"
)
login = rocket.login("user1", "password").json()
users_create_token = rocket.users_create_token(
    username="user1"
).json()
print(users_create_token)
```

`{'data': {'userId': 'PtSTvisrRL89BHDxi', 'authToken': 'a1OleTL9vSHtr9LQtIIQWhMC_jKenUxRFf_--2vXqfs'}, 'success': True}`

**Comment by lcundiff** [comment]
Ok it must be something on my end then. Apologies!
