### ISSUE TITLE
please add team related API 

### ISSUE THREAD

**Issue by lsaint** [jadolg/rocketchat_API#136]
https://developer.rocket.chat/api/rest-api/endpoints/team-collaboration-endpoints/teams/create

**Comment by jadolg** [comment]
Hi, is there anything specific from this API that you need besides the endpoint to create a new team?
The create one is on it's way https://github.com/jadolg/rocketchat_API/pull/138

**Comment by lsaint** [comment]
nice, it meet my needs now, thank you
