### ISSUE TITLE
REST API for group: kwargs are not the displayed one in exception

### ISSUE THREAD

**Issue by moobyfr** [jadolg/rocketchat_API#139]
Using groups_members  I was confronted to the name of the variables

I can use `groups_members(group="foo")`, but not `groups_members(roomId="bar")`
using the second call, I get an exception 
`RocketMissingParamException: roomId or group required`

THE REST API allows usage of roomId 

The current workaround is to use  `groups_members(room_id="bar")`

**Comment by jadolg** [comment]
We use only the required parameters for every endpoint explicitly in code. This means we will be specifically checking for `group` or `room_id`. In the end, `room_id` is transformed to `roomId` under the hood so it basically is the same. The idea was to use a naming schema following as much as possible Python's standards.
