### ISSUE TITLE
How to pass an Auth token to RocketChat API

### ISSUE THREAD

**Issue by japrogramer** [jadolg/rocketchat_API#150]
Im looking to use the oauth token to then call /api/v1/me to register a user.

How do I make that call to RocketChat with the Auth Token instead of using username and password?

**Comment by jadolg** [comment]
You could create a RocketChat object with no credentials and then set the `auth_token` for your object manually. There's no method for that because you can just directly access the attribute of the object.

**Comment by japrogramer** [comment]
thanks, that makes sense.
