### ISSUE TITLE
login method on RocketChat does not use timeout value

### ISSUE THREAD

**Issue by NickCellino** [jadolg/rocketchat_API#153]
It looks like the login method here (https://github.com/jadolg/rocketchat_API/blob/ba8fd19d82b3c13c6a7433c4c43a946cbe1d5f66/rocketchat_API/APISections/base.py#L118) directly uses `requests.post` instead of using `self.req.post` and it does not pass in the class's `timeout` value.

I am testing out what happens if my app's backend server loses connectivity to my Rocketchat server and currently, if there is a network error, my server will just hang for minutes waiting for this request because we do not pass in any timeout value.

Should we pass in the timeout value and/or use `self.req.post` instead of `requests.post`?

**Comment by jadolg** [comment]
I'll just make it so login uses the class level timeout

**Comment by NickCellino** [comment]
thank you 👍
