### ISSUE TITLE
Role endpoints are missing

### ISSUE THREAD

**Issue by andynd** [jadolg/rocketchat_API#159]
All endpoints at https://developer.rocket.chat/reference/api/rest-api/endpoints/team-collaboration-endpoints/roles-endpoints are missing

**Comment by jadolg** [comment]
Solved in https://github.com/jadolg/rocketchat_API/pull/160
I'll be publishing a new version with these changes today.

**Comment by jadolg** [comment]
Version 1.24.0 already contains this changes.
