### ISSUE TITLE
RocketAuthenticationException(No exception message supplied)

### ISSUE THREAD

**Issue by Sourabhah** [jadolg/rocketchat_API#16]
```

Request Method: | GET
-- | --
http://127.0.0.1:8000/api/v1/chat/token/
1.11.5
RocketAuthenticationException
/python3.4/site-packages/rocketchat_API/rocketchat.py in login, line 66
Thu, 22 Mar 2018 12:53:21 +0000

```

I don't Know if this is right platform for my question , i am getting this error when i get auth_token and user_id can anyone help ,
Thanks in advance

**Comment by jadolg** [comment]
Hi @Sourabhah
what version of Rocket.Chat are you using and what version of the library?

**Comment by Sourabhah** [comment]
Library version rocketchat-API==0.6.5 and Rocketchat version {"info":{"version":"0.62.1"},"success":true}

**Comment by jadolg** [comment]
@Sourabhah exactly what method are you calling in the library? Usually only login will raise a RocketAuthenticationException if user does not exist or you are using wrong credentials.

**Comment by RashmiGulati** [comment]
Hi @jadolg ,
I am really sorry for bothering it was wrong credentials issue ,i was sending phone number as username with +91, which gave me this error , Thanks for your response

**Comment by Sourabhah** [comment]
hey @jadolg ,

really sorry for bothering , it was my mistake to send phone number with +91 code , which rocket chat was not accepting , many thanks for your response

**Comment by jadolg** [comment]
No problem :) Please report any issue to continue growing strong. Thanks.
