### ISSUE TITLE
Custom channel id

### ISSUE THREAD

**Issue by Podolyan98** [jadolg/rocketchat_API#162]
When creating a channel, you must specify a name:

```
pprint(rocket.channels_create(name='Test').json())
```

Is it possible to specify a custom id for a channel?

**Comment by jadolg** [comment]
According to [the docs](https://developer.rocket.chat/reference/api/rest-api/endpoints/team-collaboration-endpoints/channels-endpoints/create#example-call) this is not possible. The `id` is calculated by the server. Maybe open an issue with rocket.chat if you need this feature.
