### ISSUE TITLE
Get unread messages

### ISSUE THREAD

**Issue by OleksaKond** [jadolg/rocketchat_API#167]
Hi,
I would like to know if there is any possibility to check for any unread messages (not only in one room, but in general)
If not, is there any API, that can return something like {message: {from: roomId}, {message: messageText}} etc. 
Thanks

**Comment by jadolg** [comment]
Maybe the subscriptions API is what you are looking for but I'm not completely sure. Maybe check the [API docs](https://developer.rocket.chat/reference/api/rest-api) for the correct endpoint and if we don't have it implemented we make it happen.
