### ISSUE TITLE
'README.md' is missing in Pypi's SDIST

### ISSUE THREAD

**Issue by onkelbeh** [jadolg/rocketchat_API#184]
```
>>> Verifying ebuild manifests
>>> Emerging (1 of 1) dev-python/rocketchat-API-0.6.1::HomeAssistantRepository
>>> Failed to emerge dev-python/rocketchat-API-0.6.1, Log file:
>>>  '/var/tmp/portage/dev-python/rocketchat-API-0.6.1/temp/build.log'
>>> Jobs: 0 of 1 complete, 1 failed                 Load avg: 1.75, 1.04, 0.65
 * Package:    dev-python/rocketchat-API-0.6.1:0
 * Repository: HomeAssistantRepository
 * Maintainer: b@edevau.net
 * Upstream:   diazorozcoj@gmail.com
 * USE:        abi_x86_64 amd64 elibc_glibc kernel_linux python_targets_python3_10 test userland_GNU
 * FEATURES:   network-sandbox preserve-libs sandbox userpriv usersandbox
>>> Unpacking source...
>>> Unpacking rocketchat-API-0.6.1.tar.gz to /var/tmp/portage/dev-python/rocketchat-API-0.6.1/work
>>> Source unpacked in /var/tmp/portage/dev-python/rocketchat-API-0.6.1/work
>>> Preparing source in /var/tmp/portage/dev-python/rocketchat-API-0.6.1/work/rocketchat_API-0.6.1 ...
 * Build system packages:
 *   dev-python/setuptools         : 65.3.0
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/dev-python/rocketchat-API-0.6.1/work/rocketchat_API-0.6.1 ...
>>> Source configured.
>>> Compiling source in /var/tmp/portage/dev-python/rocketchat-API-0.6.1/work/rocketchat_API-0.6.1 ...
 * python3_10: running distutils-r1_run_phase distutils-r1_python_compile
python3.10 setup.py build -j 6
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/rocketchat-API-0.6.1/work/rocketchat_API-0.6.1/setup.py", line 14, in <module>
    long_description=open("README.md", "r").read(),
FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
 * ERROR: dev-python/rocketchat-API-0.6.1::HomeAssistantRepository failed (compile phase):
 *   (no error message)
 *
```

**Comment by onkelbeh** [comment]
Yes, on 0.6.1. This is the version requested by Home Assistant :-)

**Comment by jadolg** [comment]
Well, I tried to fix it and I actually made it worse.
Turns out I can't really replace a file that's already uploaded to pypi.
I generated a new package and tried to upload it but it complains the file is already there.
I deleted the file from pypi and now it complains about the name being used already.

So now not even the old one works.

**Comment by jadolg** [comment]
It doesn't seem to be fixable. Please consider updating to a newer version. 0.6.1 is possibly not compatible with modern rocket.chat versions.

**Comment by onkelbeh** [comment]
Sorry that I didnt explain that more datailed yesterday, but was very tired after going through 800 commits of outdated packages as a big cleanup job (2 days in a row) :-)

I don't use your module myself, I just wanted it for completeness of [Home Assistant on Gentoo Linux.](https://github.com/onkelbeh/HomeAssistantRepository), I already thought that it will not be usable anymore as I scrolled throught your revivions. .. as I started the issue I hadn't noticed that the required module is that old. Sorry for that.

I'll check that with the code owner of HA's component part, this should be repaired / renewed.

**Comment by onkelbeh** [comment]
PS I also believe that a released package cannot (at least should not) be changed.

**Comment by jadolg** [comment]
The API itself is backward compatible only till some point.
0.6.1 was released before Rocket.Chat reached version 1 (currently it's already on version 5)
I was planning to approximate my versioning to theirs but it never went that smooth since I don't actively release any new versions unless there's a need.

**Comment by jadolg** [comment]
I'm going to close this since there's no possible solution.
