### ISSUE TITLE
How to auto answer channel message

### ISSUE THREAD

**Issue by nalakawula** [jadolg/rocketchat_API#185]
Hi, thank you for your awesome project. I am not expert in code, but i need a simple auto answer a message in a channel but i don't know how to do that. Would you mind to give example code?

Something like [this](https://github.com/RocketChat/Rocket.Chat.js.SDK#super-quick-start-30-seconds) but in python.

Thanks

**Comment by jadolg** [comment]
I made this some time ago https://github.com/jadolg/RocketChatBot
I think it might help. 
It doesn't do everything you need but it's a start.
