### ISSUE TITLE
Rocketchat Bot

### ISSUE THREAD

**Issue by seyed-dev** [jadolg/rocketchat_API#189]
# RocketPyBot
## Python lib for create rocketchat bot with getupdate like TelegramBots
i create this lib for Making a robot in the simplest way

github : https://github.com/seyed-dev/rocketchatbot
pypi : https://pypi.org/project/pyrocketbot/

**Comment by jadolg** [comment]
Hey @seyed-dev :wave: 
nice job!
Would you like to add it to our wiki?
I think it'd be a good addition to our project wiki here on GitHub so others can find it https://github.com/jadolg/rocketchat_API/wiki
There's not much going on there and maybe we can start filling it with projects and examples.
wdyt?
