### ISSUE TITLE
Is there any callback interface for us to subscribe?

### ISSUE THREAD

**Issue by HuXinjing** [jadolg/rocketchat_API#227]
Is there any callback interface for us to subscribe for? It seems we need to poll by ourselves with  _rocket.channels_history('GENERAL', count=5).json()_

**Comment by jadolg** [comment]
This library only talks to the REST API so far.
There's a [realtime API](https://developer.rocket.chat/reference/api/realtime-api) and it looks like someone wrote a wrapper for it already https://github.com/hynek-urban/rocketchat-async

**Comment by HuXinjing** [comment]
> This library only talks to the REST API so far. There's a [realtime API](https://developer.rocket.chat/reference/api/realtime-api) and it looks like someone wrote a wrapper for it already https://github.com/hynek-urban/rocketchat-async

Thx，that's exactly what I need.
