### ISSUE TITLE
users_update working?

### ISSUE THREAD

**Issue by Bart274** [jadolg/rocketchat_API#23]
Hi,

Can anyone tell me how I should use the users_update call to add a role to a user? Atm I have this code:
```
        if 'Instinct' not in roles:
            userresponse = self.api.users_info(username=user).json()['user']
            userresponse["roles"].append('Instinct')
            self.api.users_update(userid, data=userresponse)
```
However, I don't get any error but my user doesn't has his role added.

**Comment by jadolg** [comment]
Hi @Bart274 sorry for my late response. I tried this and worked perfectly:
 ```python
user = rocket.users_info(username='username').json().get('user')
roles = user.get('roles')

if 'Instinct' not in roles:
    roles.append('Instinct')
    rocket.users_update(user_id=user.get('_id'), roles=roles)
```
Just don't update everything, use only the one you actually need to update.

**Comment by Bart274** [comment]
Hi @jadolg
Thanks for your reaction, that solution worked perfectly 😊
