### ISSUE TITLE
Backport to python 2.7

### ISSUE THREAD

**Issue by jadolg** [jadolg/rocketchat_API#3]
Write modifications to backport this library for python 2.7

**Comment by codeshard** [comment]
Not sure, but is not necessary. So far I've tested all users API and there's not any incompatibility with Python 2. Ah! I just added the encoding to the python file, ensuring the encoding 'cause you have some ASCII characters.

**Comment by jadolg** [comment]
make PR with your changes ;) if it works fine with python2 I'll try building the wheel and upload it to pypi

**Comment by ali-mahdavi** [comment]
that's excellent 👍  
best regards

**Comment by jadolg** [comment]
I believe it's usable on Python 2, you just have to deal with unicode errors by yourself. I'll close this issue.
