### ISSUE TITLE
Link to the API documentation is broken (again?)

### ISSUE THREAD

**Issue by frostbtn** [jadolg/rocketchat_API#30]
Something is wrong with the link to API docs from the `README.md`. Browsing from _Rocket.chat_ front page you would end up at `https://rocket.chat/docs/developer-guides/rest-api/` not at `https://docs.rocket.chat/developer-guides/rest-api` (which time-outs for me at the moment).

However there's [Oct 20, 2017 commit](https://github.com/jadolg/rocketchat_API/commit/f1abebc8d0a76b533ee605f7aa614a872a7c7679#diff-04c6e90faac2675aa89e2176d2eec7d8) from @comodoro with change in exactly opposite direction. Maybe @comodoro has more info on why he proposed the change?

**Comment by comodoro** [comment]
If I remember correctly, the old link did not work at that time, while the committed one did. The situation is reversed now, thanks for pointing it out.
