### ISSUE TITLE
TOTP missing in auth request

### ISSUE THREAD

**Issue by lorek123** [jadolg/rocketchat_API#36]
Hello,
RocketChat supports TOTP, and currently this wrapper is missing possibility to add TOTP token to auth.
More details:
https://rocket.chat/docs/developer-guides/rest-api/authentication/login/#example-call---when-two-factor2fa-authentication-is-enabled

**Comment by jadolg** [comment]
this is going to be tricky to test :thinking:

**Comment by jadolg** [comment]
I have not found a good way of implementing this with all the needed tests. Looks like the rest of the community is in the same position. As this is a very old issue I'll close it for now.
