### ISSUE TITLE
Default log level - DEBUG

### ISSUE THREAD

**Issue by kirill-shtrykov** [jadolg/rocketchat_API#37]
In commit bd9a824328554ed0c1c629d5b396274df74e605a was enabled DEBUG level for package. In this way all calls to urllib3/requests logged to stdout. It's by design?

**Comment by jadolg** [comment]
Hi @kirill-shtrykov 
I changed the log level to WARNING on commit 065995910e352928ac02122ec38a5a5c8ef2c659 exactly because of this. DEBUG was too verbose and provided not important information for this project.

**Comment by kirill-shtrykov** [comment]
It's great, thank you!
