### ISSUE TITLE
wrong content/type at room.upload

### ISSUE THREAD

**Issue by farconada** [jadolg/rocketchat_API#48]
I'm trying to upload a png to a room. The api uploads the file but the content type at download is text/plain Would you mind to fix it?
Is it possible to upload by channel name and not only roomId?

thanks

**Comment by jadolg** [comment]
So far according to the docs you have to use the room id:
https://rocket.chat/docs/developer-guides/rest-api/rooms/upload/
I'll take a look at it ASAP.

**Comment by jadolg** [comment]
Solved on 407dbacb31f6976bf6cb5e903df64168d7732448
Will push a new release now

**Comment by jadolg** [comment]
https://pypi.org/project/rocketchat-API/
Already available on version 0.6.28
Can you confirm if it's working for you?

**Comment by farconada** [comment]
Thanks, It works
