### ISSUE TITLE
Different instances with different users not possible

### ISSUE THREAD

**Issue by smoehrle** [jadolg/rocketchat_API#50]
Hey,

due to the headers being declared like this, it is not possible to have multiple RocketChat instances with different users.
```python
class RocketChat:
    headers = {}
```
By creating and logging in with the second instance the headers of the first get overwritten. This can simple be fixed by moving the second line into the `__init__()`.

**Comment by jadolg** [comment]
I made it here 078e582e56972d05793c8fd08574d41e1cb9052d
I'm deploying the new version now.
Thanks for your contribution :)
