### ISSUE TITLE
Unable to get room messages

### ISSUE THREAD

**Issue by jubalh** [jadolg/rocketchat_API#54]
With the following test snippet

```
from rocketchat_API.rocketchat import RocketChat
from pprint import pprint

rocket = RocketChat('me', 'pw', server_url='https://my.server.org')
pprint(rocket.channels_list().json())
pprint(rocket.channels_history('channame', count=5).json())
```

I get:

```
{'error': 'The parameter "roomId" or "roomName" is required '
          '[error-roomid-param-not-provided]',
 'errorType': 'error-roomid-param-not-provided',
 'success': False}
```

Am I doing something wrong or is the library not up to date?

**Comment by jadolg** [comment]
Hi @jubalh 
Are you sure you are passing the room id and not the room name??
The API supports both but only roomId is currently implemented.

**Comment by jubalh** [comment]
>  Are you sure you are passing the room id and not the room name??

Oops! No I used the room name. Thanks!

I used `pprint(rocket.channels_list().json())` now to get the ID and tried it with that. This works.
However the channel that I'm interested in is not listed there. In the webclient it has a lock in front of it, so I assume it's somehow hidden/private?

Is there still a way to get its ID?

**Comment by jadolg** [comment]
If it has a lock it's not a channel but a group so you are not using the correct methods. For some reason the guys at Rocket.Chat decided to make all the methods for groups/channels separated. Now they have some methods with **room** which will work for both group and channel but still, most of them are separated.

**Comment by jubalh** [comment]
Oh my bad! Sorry about the confusion. My team just switched to RocketChat and I didn't really inform myself about it and just assumed all terminolgy is the same as the one I am used to.

```
pprint(rocket.groups_list().json())
pprint(rocket.groups_history('groupid', count=5).json())
```

Works as expected. Thanks for you help!
