### ISSUE TITLE
Channels.counters

### ISSUE THREAD

**Issue by Igor-ua** [jadolg/rocketchat_API#58]
Hi,
Could I ask you to update an API with:
```
def channels_counters(self, room_id, **kwargs):
        """Gets counters for a channel."""
        return self.__call_api_get('channels.counters', roomId=room_id, kwargs=kwargs)
```

Link: https://rocket.chat/docs/developer-guides/rest-api/channels/counters/

**Comment by jadolg** [comment]
Hi @Igor-ua 
This one is solved in 38bdfa61df09b05553d35be9fd794705c38ff282 :)
I'll make a release soon :)
