### ISSUE TITLE
Update to run with the latest rocket.chat version

### ISSUE THREAD

**Issue by jadolg** [jadolg/rocketchat_API#59]

**Comment by tamasgal** [comment]
Yes, the RocketChat API has changed from one day to another. Are there any updates planned?

**Comment by jadolg** [comment]
I'm already working on it whenever I have some spare time. I'm having problems executing my tests right now and I believe it might be the API rate limiter. Need to find a workaround.

**Comment by jadolg** [comment]
running tests with the new server version is already working

**Comment by tamasgal** [comment]
Wow thanks! Sorry, I could not find time to contribute. Did the public API change?

**Comment by jadolg** [comment]
@tamasgal at least the part regarding the basics did not change, but we don't track deep changes in the API on the library. That's why the idea was always returning a `requests` object and let the developers deal with it.
It was only needed to deploy the test server with some special flags so it does not block the tests.
There is one method timing out now and for the moment I did not want to stop the release because of it. I'll try to find a solution later as it is not that important and it is probably bound to the deployment of the test server anyways.
The work of @sudoguy rewriting the tests helped a lot also :)

**Comment by tamasgal** [comment]
Ok thanks! ☺️
