### ISSUE TITLE
Provide a sdist tarball

### ISSUE THREAD

**Issue by toabctl** [jadolg/rocketchat_API#6]
Please provide (in addition to the wheel file) a sdist tarball. That is useful for downstream distros (eg. openSUSE) to create packages...

**Comment by jadolg** [comment]
done!
I'll try to keep updating everytime I update the package. Thanks for your help.

**Comment by toabctl** [comment]
@jadolg there is even github/travis-CI integration. So you could setup travis to create/upload a new whl/sdist whenever you push a git tag to the repo...

**Comment by jadolg** [comment]
I'll look into it. Truth is my internet connection is so poor that I haven't being able to properly open Travis

**Comment by jadolg** [comment]
@toabctl can you open a new issue explaining what to do using Travis?
