### ISSUE TITLE
settings-methods have no kwargs

### ISSUE THREAD

**Issue by sistason** [jadolg/rocketchat_API#65]
The settings-methods (get, update, list) do not have kwargs, so I cannot iterate with count/offset over all settings, when there is an API-limit.
Is there a reason not to have kwargs there (line 644-656)? 
  If not, could you add them? Do you want a PR for this? :)

**Comment by jadolg** [comment]
There is no reason not to have them.
Please, make a PR, make sure all the tests pass and I'll merge it :-)

**Comment by jadolg** [comment]
solved in 4d6ecd3
