### ISSUE TITLE
Do not call logging.basicConfig()

### ISSUE THREAD

**Issue by Tanacki** [jadolg/rocketchat_API#72]
Hey,

I believe that calling logging.basicconfig() inside packages should be treated as anti-pattern.

As basicConfig() can be called only once, importing this package may cause basicConfig in the projects to not be processed and thus logging to not work in not an obvious way.

More information on how to do it properly can be found here:
https://stackoverflow.com/questions/27016870/how-should-logging-be-used-in-a-python-package
https://docs.python.org/3/howto/logging.html#configuring-logging-for-a-library

Important note from docs:

> Note It is strongly advised that you do not add any handlers other than NullHandler to your library’s loggers. This is because the configuration of handlers is the prerogative of the application developer who uses your library. The application developer knows their target audience and what handlers are most appropriate for their application: if you add handlers ‘under the hood’, you might well interfere with their ability to carry out unit tests and deliver logs which suit their requirements.

logging.basicConfig() does exactly that, creates a handler.

**Comment by jadolg** [comment]
travis is already building 1.2.0 which has this change.
It'll be deployed immediately :)
