### ISSUE TITLE
users_get_avatar when unauthorized

### ISSUE THREAD

**Issue by sistason** [jadolg/rocketchat_API#76]
You can enable the setting AvatarBlockUnauthorizedAccess for the avatars of the users to not be publicly available by everyone on the internet. It's an almost always basic feature to activate.

Sadly, the link you get back from the API (/avatars/username) cannot deal with the headers we send to the API to authenticate (X-Auth-Token), so blocking you from accessing your avatar. It needs rc_uid and rc_token in the Cookies, not the Headers....

Currently, in users_get_avatar, you get back a link. At the end of the method, you access that link, returning the response not from the API, but the image itself.
When we enabled the unauthorized_access-setting, the response will be a 403 - Forbidden. Seeing as we want to get the image, we could check for a 403 in the users_get_avatar-method in the end and in that case forge a request containing the token from rocket.headers as cookies.

Would you think this is too much automation in a single method, or should I do a PR for this?

**Comment by jadolg** [comment]
Your changes are already merged so I'm closing this one.
