### ISSUE TITLE
which python wrapper to use? rocketchat_API or rocket-python

### ISSUE THREAD

**Issue by xu4wang** [jadolg/rocketchat_API#78]
Dear All,

I'm new to RocketChat, looking for a python SDK for developing RocketChat bot.  I found two:

- https://github.com/jadolg/rocketchat_API
- https://github.com/Pipoline/rocket-python

Do you know which I should I choose? what's the difference?

Thanks in advance,
Austin

**Comment by jadolg** [comment]
I'm probably too biased to answer this question :-)
I'll tell you why I decided to build this one this way.
My goals where:
1. Creating a wrapper that's easy enough for everyone to contribute (regardless of repetitions in code)
2. Testing as much as possible against the actual server and not some sort of mock (tests in this project are mostly integration tests and they run at least once a week on the latest version of rocket.chat so we'll know always if it breaks)
3. Not aiming to implement everything at once, still try to provide as much as possible so more developers can take advantage of it.

This is mainly my mindset about this project. I couldn't tell if it's really better although I do believe it's more complete.

**Comment by xu4wang** [comment]
thanks @jadolg for your work on this.  The goal is great, I will verify it. :-)
