### ISSUE TITLE
send richmessage

### ISSUE THREAD

**Issue by xu4wang** [jadolg/rocketchat_API#79]
I'm trying to port below program to use rocketchat_API

https://github.com/WideChat/python-richmessage-testbot/blob/master/richmessage_bot.py

Is there an API I can use to send a richmessage?

**Comment by jadolg** [comment]
I'm not sure what you want to do there. What exactly is a "richmessage"? Can you send a "richmessage" using the sendMessage method of the API? 
https://rocket.chat/docs/developer-guides/rest-api/chat/sendmessage/

**Comment by xu4wang** [comment]
I want the Robot send a menu to the receiver, and the receiver can click the click inside the message and the selection of the receiver will be send back to the robot.

**Comment by jadolg** [comment]
as far as I understood from that thread you should be able to do it on the attachments of the message, but I'm not sure how to because it's not documented on the API docs

**Comment by xu4wang** [comment]
here there is something related to sending attachments

https://rocket.chat/docs/developer-guides/rest-api/chat/postmessage/#attachments-detail

is there a sample or test available for sending attachment? thanks @jadolg

**Comment by jadolg** [comment]
since attachments are not mandatory on the message I doubt we have tested for it. It should not be difficult to try though. The only complex field which might be problematic is `fields` and if you find problems with it we can always analyze them and try to solve them.

**Comment by xu4wang** [comment]
> since attachments are not mandatory on the message I doubt we have tested for it. It should not be difficult to try though. The only complex field which might be problematic is `fields` and if you find problems with it we can always analyze them and try to solve them.

OK. I will try it and let you know the result. :-)

**Comment by xu4wang** [comment]
@jadolg I've finished the test.  

Please find below a screenshoot:
![image](https://user-images.githubusercontent.com/311397/81368904-95b87c80-9123-11ea-94b5-15555c7ca6a8.png)

And some code snipnet below:

```
att = [{
      "title": "text button with msg in chat window",
      "actions": [
        {
          "type": "button",
          "text": "Say hello in chat window?",
          "msg": "hello in chat window",
          "msg_in_chat_window": True
        }
      ]
    }]
pprint(rocket.chat_post_message("Title""", channel='robotest', alias='Robot-Kai', attachments=att).json())
pprint(rocket.chat_post_message('', channel='robotest', alias='Robot-Kai', attachments=att).json())
pprint(rocket.chat_post_message(None, channel='robotest', alias='Robot-Kai', attachments=att).json())

```

There is one issue found, I was not able to send a richmessage without the text field.  I modified the SDK to handle this scenario. One pull request was issued for your evaluation.

https://github.com/jadolg/rocketchat_API/pull/80

**Comment by jadolg** [comment]
that's fantastic!
could you add this to the wiki so it is recorded how to do it?
as soon as your pull request (#80) passes the tests I'll merge it.

**Comment by xu4wang** [comment]
Sorry, off the topic, I was not able to find an Edit button here https://github.com/jadolg/rocketchat_API/wiki

Do I need to clone/modify and commit?

**Comment by jadolg** [comment]
My bad, I had it set incorrectly

**Comment by xu4wang** [comment]
> My bad, I had it set incorrectly

https://github.com/jadolg/rocketchat_API/wiki/Send-richmessage

initial version added.
let's improve it step by step.

**Comment by jadolg** [comment]
fantastic!
nice work!

**Comment by jadolg** [comment]
I'm going to close this issue now as it's already documented how to send richmessages on the wiki.
