### ISSUE TITLE
add 

### ISSUE THREAD

**Issue by lucianomarav** [jadolg/rocketchat_API#87]
# Rooms    
def rooms_create_discussion(self, prid, t_name, **kwargs):
        """Creates a new discussion for room"""
        return self.__call_api_post('rooms.createDiscussion', prid=prid, t_name=t_name, kwargs=kwargs)

**Comment by jadolg** [comment]
Would you like to make a pull request? ;-)

**Comment by jadolg** [comment]
Added in https://github.com/jadolg/rocketchat_API/pull/98
Will merge after the CI is done
